CREATE TABLE INV(
   ID INTEGER PRIMARY KEY	 AUTOINCREMENT,
   CODE           TEXT     NOT NULL,
   NAME           TEXT    NOT NULL,
   SIZE            TEXT    NOT NULL,
   QUANTITY		  INT	 NOT NULL,
   TYPE           TEXT    NOT NULL,
   LOCATION       TEXT		NOT NULL,
   PICTURE			TEXT	NOT NULL
);